/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.model;

import java.util.Objects;
import chemadvisor.chemApi.model.EntryChemicalData;
import chemadvisor.chemApi.model.Identifiers;
import chemadvisor.chemApi.model.Links;
import chemadvisor.chemApi.model.SubstanceNames;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contains substance level data
 */
@ApiModel(description = "Contains substance level data")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T09:50:52.511-05:00")
public class Entry   {
  @SerializedName("_id")
  private String id = null;

  @SerializedName("substance_id")
  private Integer substanceId = null;

  @SerializedName("regulatory_list_id")
  private Integer regulatoryListId = null;

  @SerializedName("release_id")
  private Integer releaseId = null;

  @SerializedName("identifiers")
  private Identifiers identifiers = null;

  @SerializedName("names")
  private SubstanceNames names = null;

  @SerializedName("chemical_data")
  private EntryChemicalData chemicalData = null;

  @SerializedName("links")
  private Links links = null;

  public Entry id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Entry substanceId(Integer substanceId) {
    this.substanceId = substanceId;
    return this;
  }

   /**
   * Get substanceId
   * @return substanceId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getSubstanceId() {
    return substanceId;
  }

  public void setSubstanceId(Integer substanceId) {
    this.substanceId = substanceId;
  }

  public Entry regulatoryListId(Integer regulatoryListId) {
    this.regulatoryListId = regulatoryListId;
    return this;
  }

   /**
   * Get regulatoryListId
   * @return regulatoryListId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getRegulatoryListId() {
    return regulatoryListId;
  }

  public void setRegulatoryListId(Integer regulatoryListId) {
    this.regulatoryListId = regulatoryListId;
  }

  public Entry releaseId(Integer releaseId) {
    this.releaseId = releaseId;
    return this;
  }

   /**
   * Get releaseId
   * @return releaseId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getReleaseId() {
    return releaseId;
  }

  public void setReleaseId(Integer releaseId) {
    this.releaseId = releaseId;
  }

  public Entry identifiers(Identifiers identifiers) {
    this.identifiers = identifiers;
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/
  @ApiModelProperty(example = "null", value = "")
  public Identifiers getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(Identifiers identifiers) {
    this.identifiers = identifiers;
  }

  public Entry names(SubstanceNames names) {
    this.names = names;
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public SubstanceNames getNames() {
    return names;
  }

  public void setNames(SubstanceNames names) {
    this.names = names;
  }

  public Entry chemicalData(EntryChemicalData chemicalData) {
    this.chemicalData = chemicalData;
    return this;
  }

   /**
   * Get chemicalData
   * @return chemicalData
  **/
  @ApiModelProperty(example = "null", value = "")
  public EntryChemicalData getChemicalData() {
    return chemicalData;
  }

  public void setChemicalData(EntryChemicalData chemicalData) {
    this.chemicalData = chemicalData;
  }

  public Entry links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entry entry = (Entry) o;
    return Objects.equals(this.id, entry.id) &&
        Objects.equals(this.substanceId, entry.substanceId) &&
        Objects.equals(this.regulatoryListId, entry.regulatoryListId) &&
        Objects.equals(this.releaseId, entry.releaseId) &&
        Objects.equals(this.identifiers, entry.identifiers) &&
        Objects.equals(this.names, entry.names) &&
        Objects.equals(this.chemicalData, entry.chemicalData) &&
        Objects.equals(this.links, entry.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, substanceId, regulatoryListId, releaseId, identifiers, names, chemicalData, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    substanceId: ").append(toIndentedString(substanceId)).append("\n");
    sb.append("    regulatoryListId: ").append(toIndentedString(regulatoryListId)).append("\n");
    sb.append("    releaseId: ").append(toIndentedString(releaseId)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    chemicalData: ").append(toIndentedString(chemicalData)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

