/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Language
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T09:50:52.511-05:00")
public class Language   {
  @SerializedName("iso_639_1_language")
  private String iso6391Language = null;

  @SerializedName("iso_639_1_code")
  private String iso6391Code = null;

  public Language iso6391Language(String iso6391Language) {
    this.iso6391Language = iso6391Language;
    return this;
  }

   /**
   * Get iso6391Language
   * @return iso6391Language
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getIso6391Language() {
    return iso6391Language;
  }

  public void setIso6391Language(String iso6391Language) {
    this.iso6391Language = iso6391Language;
  }

  public Language iso6391Code(String iso6391Code) {
    this.iso6391Code = iso6391Code;
    return this;
  }

   /**
   * Get iso6391Code
   * @return iso6391Code
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getIso6391Code() {
    return iso6391Code;
  }

  public void setIso6391Code(String iso6391Code) {
    this.iso6391Code = iso6391Code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Language language = (Language) o;
    return Objects.equals(this.iso6391Language, language.iso6391Language) &&
        Objects.equals(this.iso6391Code, language.iso6391Code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iso6391Language, iso6391Code);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Language {\n");
    
    sb.append("    iso6391Language: ").append(toIndentedString(iso6391Language)).append("\n");
    sb.append("    iso6391Code: ").append(toIndentedString(iso6391Code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

