/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.model;

import java.util.Objects;
import chemadvisor.chemApi.model.BaseDataType;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Range
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T09:50:52.511-05:00")
public class Range extends BaseDataType  {
  @SerializedName("lower_op")
  private String lowerOp = null;

  @SerializedName("lower_val")
  private Double lowerVal = null;

  @SerializedName("upper_op")
  private String upperOp = null;

  @SerializedName("upper_val")
  private Double upperVal = null;

  @SerializedName("unit")
  private String unit = null;

  @SerializedName("unit_type")
  private String unitType = null;

  public Range lowerOp(String lowerOp) {
    this.lowerOp = lowerOp;
    return this;
  }

   /**
   * Get lowerOp
   * @return lowerOp
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLowerOp() {
    return lowerOp;
  }

  public void setLowerOp(String lowerOp) {
    this.lowerOp = lowerOp;
  }

  public Range lowerVal(Double lowerVal) {
    this.lowerVal = lowerVal;
    return this;
  }

   /**
   * Get lowerVal
   * @return lowerVal
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Double getLowerVal() {
    return lowerVal;
  }

  public void setLowerVal(Double lowerVal) {
    this.lowerVal = lowerVal;
  }

  public Range upperOp(String upperOp) {
    this.upperOp = upperOp;
    return this;
  }

   /**
   * Get upperOp
   * @return upperOp
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUpperOp() {
    return upperOp;
  }

  public void setUpperOp(String upperOp) {
    this.upperOp = upperOp;
  }

  public Range upperVal(Double upperVal) {
    this.upperVal = upperVal;
    return this;
  }

   /**
   * Get upperVal
   * @return upperVal
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Double getUpperVal() {
    return upperVal;
  }

  public void setUpperVal(Double upperVal) {
    this.upperVal = upperVal;
  }

  public Range unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public Range unitType(String unitType) {
    this.unitType = unitType;
    return this;
  }

   /**
   * Get unitType
   * @return unitType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUnitType() {
    return unitType;
  }

  public void setUnitType(String unitType) {
    this.unitType = unitType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Range range = (Range) o;
    return Objects.equals(this.lowerOp, range.lowerOp) &&
        Objects.equals(this.lowerVal, range.lowerVal) &&
        Objects.equals(this.upperOp, range.upperOp) &&
        Objects.equals(this.upperVal, range.upperVal) &&
        Objects.equals(this.unit, range.unit) &&
        Objects.equals(this.unitType, range.unitType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lowerOp, lowerVal, upperOp, upperVal, unit, unitType, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Range {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    lowerOp: ").append(toIndentedString(lowerOp)).append("\n");
    sb.append("    lowerVal: ").append(toIndentedString(lowerVal)).append("\n");
    sb.append("    upperOp: ").append(toIndentedString(upperOp)).append("\n");
    sb.append("    upperVal: ").append(toIndentedString(upperVal)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    unitType: ").append(toIndentedString(unitType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

