/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.model;

import java.util.Objects;
import chemadvisor.chemApi.model.Links;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * RegulatoryListChange
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T09:50:52.511-05:00")
public class RegulatoryListChange   {
  @SerializedName("change_type")
  private String changeType = null;

  @SerializedName("regulatory_list_id")
  private Integer regulatoryListId = null;

  @SerializedName("release_id")
  private Integer releaseId = null;

  @SerializedName("links")
  private Links links = null;

  public RegulatoryListChange changeType(String changeType) {
    this.changeType = changeType;
    return this;
  }

   /**
   * Get changeType
   * @return changeType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getChangeType() {
    return changeType;
  }

  public void setChangeType(String changeType) {
    this.changeType = changeType;
  }

  public RegulatoryListChange regulatoryListId(Integer regulatoryListId) {
    this.regulatoryListId = regulatoryListId;
    return this;
  }

   /**
   * Get regulatoryListId
   * @return regulatoryListId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getRegulatoryListId() {
    return regulatoryListId;
  }

  public void setRegulatoryListId(Integer regulatoryListId) {
    this.regulatoryListId = regulatoryListId;
  }

  public RegulatoryListChange releaseId(Integer releaseId) {
    this.releaseId = releaseId;
    return this;
  }

   /**
   * Get releaseId
   * @return releaseId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getReleaseId() {
    return releaseId;
  }

  public void setReleaseId(Integer releaseId) {
    this.releaseId = releaseId;
  }

  public RegulatoryListChange links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegulatoryListChange regulatoryListChange = (RegulatoryListChange) o;
    return Objects.equals(this.changeType, regulatoryListChange.changeType) &&
        Objects.equals(this.regulatoryListId, regulatoryListChange.regulatoryListId) &&
        Objects.equals(this.releaseId, regulatoryListChange.releaseId) &&
        Objects.equals(this.links, regulatoryListChange.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeType, regulatoryListId, releaseId, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegulatoryListChange {\n");
    
    sb.append("    changeType: ").append(toIndentedString(changeType)).append("\n");
    sb.append("    regulatoryListId: ").append(toIndentedString(regulatoryListId)).append("\n");
    sb.append("    releaseId: ").append(toIndentedString(releaseId)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

