/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.model;

import java.util.Objects;
import chemadvisor.chemApi.model.Entries;
import chemadvisor.chemApi.model.Languages;
import chemadvisor.chemApi.model.Links;
import chemadvisor.chemApi.model.Tags;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contains Substance Level Regulatory or Non-Regulatory Data
 */
@ApiModel(description = "Contains Substance Level Regulatory or Non-Regulatory Data")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T09:50:52.511-05:00")
public class RegulatoryList   {
  @SerializedName("_id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("navigator_link")
  private String navigatorLink = null;

  @SerializedName("source_link")
  private String sourceLink = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("is_inventory")
  private Boolean isInventory = false;

  @SerializedName("source_languages")
  private Languages sourceLanguages = null;

  @SerializedName("tags")
  private Tags tags = null;

  @SerializedName("entries")
  private Entries entries = null;

  @SerializedName("links")
  private Links links = null;

  public RegulatoryList id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RegulatoryList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RegulatoryList navigatorLink(String navigatorLink) {
    this.navigatorLink = navigatorLink;
    return this;
  }

   /**
   * Get navigatorLink
   * @return navigatorLink
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNavigatorLink() {
    return navigatorLink;
  }

  public void setNavigatorLink(String navigatorLink) {
    this.navigatorLink = navigatorLink;
  }

  public RegulatoryList sourceLink(String sourceLink) {
    this.sourceLink = sourceLink;
    return this;
  }

   /**
   * Get sourceLink
   * @return sourceLink
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceLink() {
    return sourceLink;
  }

  public void setSourceLink(String sourceLink) {
    this.sourceLink = sourceLink;
  }

  public RegulatoryList description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RegulatoryList isInventory(Boolean isInventory) {
    this.isInventory = isInventory;
    return this;
  }

   /**
   * Get isInventory
   * @return isInventory
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsInventory() {
    return isInventory;
  }

  public void setIsInventory(Boolean isInventory) {
    this.isInventory = isInventory;
  }

  public RegulatoryList sourceLanguages(Languages sourceLanguages) {
    this.sourceLanguages = sourceLanguages;
    return this;
  }

   /**
   * Get sourceLanguages
   * @return sourceLanguages
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Languages getSourceLanguages() {
    return sourceLanguages;
  }

  public void setSourceLanguages(Languages sourceLanguages) {
    this.sourceLanguages = sourceLanguages;
  }

  public RegulatoryList tags(Tags tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public Tags getTags() {
    return tags;
  }

  public void setTags(Tags tags) {
    this.tags = tags;
  }

  public RegulatoryList entries(Entries entries) {
    this.entries = entries;
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(example = "null", value = "")
  public Entries getEntries() {
    return entries;
  }

  public void setEntries(Entries entries) {
    this.entries = entries;
  }

  public RegulatoryList links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegulatoryList regulatoryList = (RegulatoryList) o;
    return Objects.equals(this.id, regulatoryList.id) &&
        Objects.equals(this.name, regulatoryList.name) &&
        Objects.equals(this.navigatorLink, regulatoryList.navigatorLink) &&
        Objects.equals(this.sourceLink, regulatoryList.sourceLink) &&
        Objects.equals(this.description, regulatoryList.description) &&
        Objects.equals(this.isInventory, regulatoryList.isInventory) &&
        Objects.equals(this.sourceLanguages, regulatoryList.sourceLanguages) &&
        Objects.equals(this.tags, regulatoryList.tags) &&
        Objects.equals(this.entries, regulatoryList.entries) &&
        Objects.equals(this.links, regulatoryList.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, navigatorLink, sourceLink, description, isInventory, sourceLanguages, tags, entries, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegulatoryList {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    navigatorLink: ").append(toIndentedString(navigatorLink)).append("\n");
    sb.append("    sourceLink: ").append(toIndentedString(sourceLink)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isInventory: ").append(toIndentedString(isInventory)).append("\n");
    sb.append("    sourceLanguages: ").append(toIndentedString(sourceLanguages)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

