/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.model;

import java.util.Objects;
import chemadvisor.chemApi.model.Identifiers;
import chemadvisor.chemApi.model.Links;
import chemadvisor.chemApi.model.RelatedSubstances;
import chemadvisor.chemApi.model.SubstanceNames;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Contains information about the substance
 */
@ApiModel(description = "Contains information about the substance")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T09:50:52.511-05:00")
public class Substance   {
  @SerializedName("_id")
  private Integer id = null;

  @SerializedName("primary_name")
  private String primaryName = null;

  @SerializedName("regulatory_burden")
  private Float regulatoryBurden = null;

  @SerializedName("identifiers")
  private Identifiers identifiers = null;

  @SerializedName("names")
  private SubstanceNames names = null;

  @SerializedName("related_substances")
  private RelatedSubstances relatedSubstances = null;

  @SerializedName("links")
  private Links links = null;

  public Substance id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Substance primaryName(String primaryName) {
    this.primaryName = primaryName;
    return this;
  }

   /**
   * Get primaryName
   * @return primaryName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPrimaryName() {
    return primaryName;
  }

  public void setPrimaryName(String primaryName) {
    this.primaryName = primaryName;
  }

  public Substance regulatoryBurden(Float regulatoryBurden) {
    this.regulatoryBurden = regulatoryBurden;
    return this;
  }

   /**
   * Get regulatoryBurden
   * @return regulatoryBurden
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getRegulatoryBurden() {
    return regulatoryBurden;
  }

  public void setRegulatoryBurden(Float regulatoryBurden) {
    this.regulatoryBurden = regulatoryBurden;
  }

  public Substance identifiers(Identifiers identifiers) {
    this.identifiers = identifiers;
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/
  @ApiModelProperty(example = "null", value = "")
  public Identifiers getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(Identifiers identifiers) {
    this.identifiers = identifiers;
  }

  public Substance names(SubstanceNames names) {
    this.names = names;
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @ApiModelProperty(example = "null", value = "")
  public SubstanceNames getNames() {
    return names;
  }

  public void setNames(SubstanceNames names) {
    this.names = names;
  }

  public Substance relatedSubstances(RelatedSubstances relatedSubstances) {
    this.relatedSubstances = relatedSubstances;
    return this;
  }

   /**
   * Get relatedSubstances
   * @return relatedSubstances
  **/
  @ApiModelProperty(example = "null", value = "")
  public RelatedSubstances getRelatedSubstances() {
    return relatedSubstances;
  }

  public void setRelatedSubstances(RelatedSubstances relatedSubstances) {
    this.relatedSubstances = relatedSubstances;
  }

  public Substance links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Substance substance = (Substance) o;
    return Objects.equals(this.id, substance.id) &&
        Objects.equals(this.primaryName, substance.primaryName) &&
        Objects.equals(this.regulatoryBurden, substance.regulatoryBurden) &&
        Objects.equals(this.identifiers, substance.identifiers) &&
        Objects.equals(this.names, substance.names) &&
        Objects.equals(this.relatedSubstances, substance.relatedSubstances) &&
        Objects.equals(this.links, substance.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, primaryName, regulatoryBurden, identifiers, names, relatedSubstances, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Substance {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    primaryName: ").append(toIndentedString(primaryName)).append("\n");
    sb.append("    regulatoryBurden: ").append(toIndentedString(regulatoryBurden)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    relatedSubstances: ").append(toIndentedString(relatedSubstances)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

