/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package chemadvisor.chemApi.client;

import chemadvisor.chemApi.ApiException;
import chemadvisor.chemApi.model.ApiResponseMessage;
import chemadvisor.chemApi.model.Entries;
import chemadvisor.chemApi.model.Entry;
import chemadvisor.chemApi.model.RegulatoryList;
import chemadvisor.chemApi.model.RegulatoryLists;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ListsApi
 */
public class ListsApiTest {

    private final ListsApi api = new ListsApi();

    
    /**
     * Return a paginated collection of entries for a single Regulatory List
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEntriesTest() throws ApiException {
        String regulatoryListId = null;
        Integer limit = null;
        Integer offset = null;
        String q = null;
        String appKey = null;
        String appId = null;
        // Entries response = api.getEntries(regulatoryListId, limit, offset, q, appKey, appId);

        // TODO: test validations
    }
    
    /**
     * Find the entries for a specific Substance on List
     *
     * Returns a collection of entries for a single Substance from a single Regulatory List
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEntryTest() throws ApiException {
        String regulatoryListId = null;
        String substanceId = null;
        String appKey = null;
        String appId = null;
        // Entry response = api.getEntry(regulatoryListId, substanceId, appKey, appId);

        // TODO: test validations
    }
    
    /**
     * Find a Regulatory List by ID
     *
     * Returns a single Regulatory List
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        String regulatoryListId = null;
        String appKey = null;
        String appId = null;
        // RegulatoryList response = api.getList(regulatoryListId, appKey, appId);

        // TODO: test validations
    }
    
    /**
     * All Lists
     *
     * A paginated collection of Regulatory Lists
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String q = null;
        String appKey = null;
        String appId = null;
        // RegulatoryLists response = api.getLists(limit, offset, q, appKey, appId);

        // TODO: test validations
    }
    
}
